ALTER TABLE documents
  ADD COLUMN IF NOT EXISTS sent_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS sent_ip VARCHAR(45),
  ADD COLUMN IF NOT EXISTS sent_by_name VARCHAR(255),
  ADD COLUMN IF NOT EXISTS sent_by_email VARCHAR(255);
